### ISSUE TITLE
영어 프로젝트 TAbhay/Hactoberfest-2021가 Excluded project가 되었습니다.

### ISSUE THREAD

**Issue by Typiespectre** [phg98/hacktoberfestkorea#137]
**문제점**
며칠 전, [TAbhay/Hactoberfest-2021](https://github.com/TAbhay/Hactoberfest-2021)에 풀 리퀘스트를 올렸었는데,
오늘 핵토버페스트 상태를 확인해보니, Excluded project라고 뜨면서, 카운팅이 되지 않는 것 같습니다.

**개선방안**
다른 초보자용 프로젝트를 선정하는 것이 좋을 것 같습니다.
다만 위처럼 Excluded Project가 아닌 프로젝트의 기준을 명확하게 잘 모르겠네요...

**Comment by phg98** [comment]
중요한 정보 감사합니다.
너무 쉽게 PR을 올릴수 있는 프로젝트는 제외하는것 같군요. ㅠㅠ
