### ISSUE TITLE
facebook에서 url입력하면 이미지가 안뜬다.

### ISSUE THREAD

**Issue by phg98** [phg98/hacktoberfestkorea#14]
**문제점**
facebook에서 https://www.hacktoberfestkorea.com/ 입력하면 이미지가 안뜬다.
![image](https://user-images.githubusercontent.com/12092302/94649608-f85b2080-032f-11eb-85f6-dfc013c49f80.png)
[facebook 공유디버거](https://developers.facebook.com/tools/debug/?locale=ko_KR)에 url넣어보면 아래와 같이 나온다.
![image](https://user-images.githubusercontent.com/12092302/94649814-67387980-0330-11eb-8ba3-5f8d7885dd42.png)

**개선방안**
웹사이트 세팅에서 뭔가 변경이 필요한듯?

**Comment by phg98** [comment]
참고
https://ogp.me/?fbclid=IwAR1zDD63si1-bAEuHskgsEM2eHnnFTFGderZwwPd0HNJq9ckj5Ca4b9KGXs
https://rohancragg.co.uk/writing/social-media-sharing/
https://github.com/rohancragg/blog-notes
https://squidfunk.github.io/mkdocs-material/reference/meta-tags/
https://squidfunk.github.io/mkdocs-material/customization/#overriding-template-blocks
https://www.mkdocs.org/user-guide/styling-your-docs/#overriding-template-blocks
https://github.com/squidfunk/mkdocs-material/issues/663

**Comment by phg9898** [comment]
수정중입니다.

**Comment by phg98** [comment]
완료
open graph 프로토콜을 메타데이터에 추가.
추가방법은 theme폴더에 overide 설정하면됨.
위에 있는 참고 링크들에 나와있다.
