### ISSUE TITLE
Discord로 소통하는 채팅방을 만들기

### ISSUE THREAD

**Issue by lill74** [phg98/hacktoberfestkorea#16]
**문제점**

Hacktoberfest 웹사이트 접속해보면, Discord 채팅방이 있어서 이벤트를 진행하는동안 실시간으로 대화하며
대회를 진행합니다. 저희도 만들어보는게 어떨까요?

**Comment by phg98** [comment]
좋은 아이디어인데, 제가 잘 몰라서 그런데 혹시 이걸 만들면 제가 그 방에 상주해야 하는건가요? ㅎㅎㅎㅎ
누가 방에 들어오면 저에게 알람같은게 오는 것인지...
궁금합니다만, 간단한 거면 한 번 만들어 놓고 지켜봐도 좋을것 같습니다.

**Comment by lill74** [comment]
그냥 만들어 놓으면 서로 소통할수 있는겁니다! 카카오톡 단톡인데, 좀더 세련된 채팅방이라고 해야할까요??

**Comment by phg98** [comment]
👍

**Comment by minhoryang** [comment]
링크 기다리겠습니다!

**Comment by AkiaCode** [comment]
저도요!

**Comment by phg98** [comment]
ㅎㅎ 요거는 @lill74 님이 선점하신 이슈입니다. 근데 lill74님 요즘 바쁘신듯 해요. lill74님! 바쁘시면 다른 분한테 넘기셔도 될것같슴돠!

**Comment by phg98** [comment]
역시 대박이시군요 짱짱
