### ISSUE TITLE
'공식홈페이지로 가기' 개선

### ISSUE THREAD

**Issue by phg98** [phg98/hacktoberfestkorea#172]
**문제점**
'공식홈페이지로 가기' 버튼이 너무 심심하다

**개선방안**
버튼을 공식홈 이미지로 바꾸면 좋을것 같아요~

**Comment by KKWANH** [comment]
제가 해보겠습니다!

**Comment by Djunnni** [comment]
이미지로 고려하고 계셨던 게 있으실까요? 제가 해보려구요

**Comment by phg98** [comment]
네 감사합니다

**Comment by LeGrandMAG** [comment]
혹시 공식홈 이미지라는 것은 버튼에 이미지 추가하는 것을 원하시거나 버튼 대신에 사진 원하시는겁니까?

**Comment by LeGrandMAG** [comment]
일단 제가 1번이랑 2번 수정했습니다. 

## 1번은 
![image](https://user-images.githubusercontent.com/64711820/206875181-0b2eb258-8087-4618-909a-df9628bf8f37.png)

## 2번은

![image](https://user-images.githubusercontent.com/64711820/206875202-94e6e512-022e-4de8-b749-2025743c8d2d.png)

어떤것 괜찮은지 말씀 하여주시면 PR하겠습니다

**Comment by phg98** [comment]
2번이 더 좋네요. 아주 깔끔해서 매우 좋습니다 ㅎㅎㅎㅎ
