### ISSUE TITLE
참여자 리스트 링크 오류

### ISSUE THREAD

**Issue by Najeong-Kim** [phg98/hacktoberfestkorea#178]
**문제점**
phg98님 소개 링크가 이중으로 들어가있어서 잘못된 곳으로 이동합니다!

`[phg98]([https://blog.naver.com/phg98/222101443689](https://www.facebook.com/photo/?fbid=5370410346375201&set=gm.1255139231909305&idorvanity=788404381916128))`

![image](https://user-images.githubusercontent.com/73640737/194683217-dfb9b4b0-f708-4cd5-ad17-d86bc31c0226.png)

**개선방안**
링크 수정이 필요합니다

**Comment by Najeong-Kim** [comment]
@phg98 님께서 확인을 해주셔야 하는 이슈입니다!

**Comment by phg98** [comment]
어휴 감사합니다!!!
