### ISSUE TITLE
초초초보자용 사용법 가이드 추가

### ISSUE THREAD

**Issue by phg9898** [phg98/hacktoberfestkorea#18]
**문제점**
초보자들이 사이트에 기여하려고 해도 방법을 모를것 같다.

**개선방안**
초보자용 사용법 가이드를 추가하자.
단순 오자 수정과 링크 추가 정도만 가능할 수준으로 알려주고,
로컬머신에서 빌드하지 않고 포크해서 깃헙에디터에서 수정하는 정도만 알려주자.
포크/브랜치/PR등 깃헙기본사용법은 링크로 처리해도 괜찮겠다.

**Comment by phg98** [comment]
그리고, 조금 더 덜 초보자를 위해서는 아래 링크 내용이 적당할 듯 (로컬머신에 클론하고 브랜치만드는 법 포함) 근데 영어
https://github.com/firstcontributions/first-contributions/blob/master/README.md
