### ISSUE TITLE
한국개발자들의 저장소에는 이슈 라벨에 'Hacktoberfest'외에도 '핵토버페스트'라고 달면 좋겠다.

### ISSUE THREAD

**Issue by phg98** [phg98/hacktoberfestkorea#4]
한국개발자들의 이슈를 쉽게 검색하기 위해 '핵토버페스트'라벨을 달아주면 좋을 듯.

**Comment by minhoryang** [comment]
<img width="400" alt="스크린샷 2020-10-06 오후 1 39 51" src="https://user-images.githubusercontent.com/1270855/95159623-75c3dc80-07d9-11eb-9794-7a877ee45217.png">

<img width="800" alt="스크린샷 2020-10-06 오후 1 40 29" src="https://user-images.githubusercontent.com/1270855/95159656-86745280-07d9-11eb-8f2b-27cacbb6cbec.png">
> "Error saving your changes: Repository topics Topics must start with a lowercase letter or number, consist of 35 characters or less, and can include hyphens."

**Comment by phg98** [comment]
제가 알아보지도않고 막 적었군요. 알려주셔서 감사감사합니다!🙏

**Comment by phg98** [comment]
앗 근데 토픽에는 한글이 안되고 이슈에는 한글이 되는것 아닐까요? 퇴근하면 확인해볼께용!😀

**Comment by minhoryang** [comment]
@phg98 아하 이슈라벨 말씀하셨군요. 제가 잘못 읽고 시도했네요!
