### ISSUE TITLE
FAQ Rule 추가

### ISSUE THREAD

**Issue by Limm-jk** [phg98/hacktoberfestkorea#44]
안녕하세요!! Hacktoberfest에 관심을 가지며 오픈소스에 처음 발을 딛는 학생개발자입니다!!
많은 분들의 뜻 깊은 활동 덕에 열심히 배워가며 성장해가는 것 같습니다.
감사합니다!!

**문제점**
Korea 사이트의 FAQ에 중요한 내용만 정리해서 올려주신 점 너무 감사하게 생각합니다.
하지만, Rule 부분의 설명도 들어있으면 좋겠다는 생각을 했습니다.

**개선방안**
Rule부분 번역 후, PR..? FAQ부분에 추가로 더 필요한 정보가 있다고 생각하시는 분은 멘션 남겨주시면 감사하겠습니다!!

**Comment by phg98** [comment]
예리한 지적이십니다. 혹시 직접 번역해서 pr보내실거면 시작한다고 적어주세요. 요즘 번역하는분들이 계셔서 겹칠까봐서요.

**Comment by Limm-jk** [comment]
번역 후 pr 하겠습니다.
