### ISSUE TITLE
hacktoberfest가 5일을 기점으로 규칙이 바꿨습니다

### ISSUE THREAD

**Issue by AkiaCode** [phg98/hacktoberfestkorea#53]
Updated (10/05/2020 15:00 UTC): Individual pull requests can also be directly opted-in to Hacktoberfest with the ‘hacktoberfest-accepted’ label, on any public GitHub repository, without the need for the ‘hacktoberfest’ repository topic.

https://hacktoberfest.digitalocean.com/hacktoberfest-update

그래서 그런지 불안하게 시간이 흘러가네요 ㅋㅋㅋ
![스크린샷, 2020-10-06 18-09-04](https://user-images.githubusercontent.com/71239005/95182030-0bbe2e00-07ff-11eb-8d79-c9daf5a787f8.png)

**Comment by phg98** [comment]
^^ 보내주신것은 머지했습니다. ^^

**Comment by AkiaCode** [comment]
넵 :smile:

**Comment by AkiaCode** [comment]
저 규칙 때문에 더 어려워 질 거 같군요 ._.

**Comment by AkiaCode** [comment]
PR는 꾸억 꾸억 해서 4개는 되었는 데 라벨 때문에 막히군요 (ㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠ)
