### ISSUE TITLE
참여 규칙이 보이지 않습니다.

### ISSUE THREAD

**Issue by mihilt** [phg98/hacktoberfestkorea#65]
**문제점**
![image](https://user-images.githubusercontent.com/50368758/95373682-48ca1380-0918-11eb-9448-f07b9adad806.png)

위의 사진처럼 참여 규칙에 관한 제목이 누락되어있습니다.

**개선방안**

개행이 필요합니다.

**Comment by phg98** [comment]
예리하시군요!🧐

**Comment by mihilt** [comment]
헉 제가 하려고 아껴두고 있었는데!!

**Comment by phg98** [comment]
저런, 그래서 이슈에다가  하겠다고 적어놔야 하더군요. 제가 기억을 못했어서 죄송하네요. 대신 하나 할 꺼리를 드리자면 웹페이지 끝에 페북으로 가는 링크가 있으면 좋겠지요
