### ISSUE TITLE
Code of Conduct 번역하여 추가하기

### ISSUE THREAD

**Issue by phg98** [phg98/hacktoberfestkorea#7]
https://docs.google.com/document/d/1gFKOhyUqMZzrZcbq8A_TpO5x9J9HK6agv70awCH8pyI/edit#heading=h.mpz2is7k9ovi
내용중에 Quick Version만이라도 번역해서 추가하자.

**Comment by jehunseo** [comment]
번역에 참여 가능할까요?

**Comment by phg98** [comment]
감사감사 왕감사입니다. 가시죠!

**Comment by jehunseo** [comment]
감사합니다!
번역 파일은 어떻게 제출하면 될까요?
위 링크 수정 액세스를 받아서 작업하면 되나요?

**Comment by phg98** [comment]
아 깃헙의 풀리퀘스트 보내는 것에 익숙하지 않으신가요? 
핵토버페스트 참가중이시면 풀리퀘스트 1개 달성할수 있으니 풀리퀘스트로 보내주시면 윈-윈 이겠습니다.
모르시면 일단 번역된후에 메세지 보내주시면 제가 알려드릴께요.

**Comment by jehunseo** [comment]
아 docs에 추가하면 되는거였군요!
해당 파일이 없어서 어떻게 내야 하나 고민하던 차였습니다. 바로 PR 올리겠습니다!
