### ISSUE TITLE
빌드 및 실행 방법 문서 필요

### ISSUE THREAD

**Issue by phg98** [phg98/hacktoberfestkorea#8]
**문제점**
현재 Material by mkDocs로 만들어져 있는데, 어떻게 빌드 및 실행해야 하는지 모르는 분들이 계실 듯합니다.

**해결방안**
로컬 환경 및 github-pages 세팅방법을 설명한 간단한 문서를 추가한다.(또는 readme에 내용 추가)

**Comment by lill74** [comment]
Pull Request #17 빌드 방법 추가했습니다!
